// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://onazaexamrdpraiakxab.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uYXphZXhhbXJkcHJhaWFreGFiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAyMDYzMjksImV4cCI6MjA2NTc4MjMyOX0.wx647NgtoTzsFP1_uR298fN3eIE50IMOHhC4AC-e9SM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);